name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [synchronize, opened]

jobs:
  build:
    if: ${{ github.event_name == 'push' && contains(join(toJson(github.event.commits.*.message)), '#skip')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-2022" #Must be unique in Heroku
          heroku_email: "mkkaarto@gmail.com"
          healthcheck: "https://pokedex-2022.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          